# Generated by Django 6.0.3 on 2026-03-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='original/')),
                ('tampered_image', models.ImageField(blank=True, null=True, upload_to='tampered/')),
                ('modification_type', models.CharField(blank=True, max_length=100, null=True)),
                ('predicted_result', models.BooleanField(null=True)),
                ('actual_result', models.BooleanField(null=True)),
                ('confidence', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
