# Generated by Django 6.0.3 on 2026-03-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageanalysis',
            name='exif_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
