# Generated by Django 6.0.3 on 2026-03-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_imageanalysis_exif_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageanalysis',
            name='clone_confidence',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='clone_tampered',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='metadata_analysis',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='metadata_confidence',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='metadata_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='metadata_file_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='metadata_image_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='metadata_pil_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='metadata_tampered',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='noise_confidence',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='noise_tampered',
            field=models.BooleanField(null=True),
        ),
    ]
