# Generated by Django 6.0.3 on 2026-03-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0003_imageanalysis_clone_confidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('total_samples', models.PositiveIntegerField(default=0)),
                ('true_positive', models.PositiveIntegerField(default=0)),
                ('true_negative', models.PositiveIntegerField(default=0)),
                ('false_positive', models.PositiveIntegerField(default=0)),
                ('false_negative', models.PositiveIntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('precision', models.FloatField(default=0.0)),
                ('recall', models.FloatField(default=0.0)),
                ('f1', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
